# Generated by Django 5.1.1 on 2024-10-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0004_rename_name_hobby_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
