# Generated by Django 5.1.1 on 2024-10-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0006_alter_project_live_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="wanted_position",
            field=models.TextField(default="Undefined"),
            preserve_default=False,
        ),
    ]
