# Generated by Django 5.1.1 on 2024-10-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0007_personalinfo_wanted_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="linkedin_username",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
